export const VIDEOS_LOADING = 'VIDEOS_LOADING';
export const VIDEOS_FAILED = 'VIDEOS_FAILED';
export const ADD_VIDEOS = 'ADD_VIDEOS';
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const APPEND_VIDEO = 'APPEND_VIDEO';
