export const SUBSCRIBTIONS_LOADING = 'SUBSCRIBTIONS_LOADING';
export const SUBSCRIBTIONS_FAILED = 'SUBSCRIBTIONS_FAILED';
export const ADD_SUBSCRIBTIONS = 'ADD_SUBSCRIBTIONS';
export const UNSUBSCRIBE = 'UNSUBSCRIBE';
export const SUBSCIBE = 'SUBSCIBE';